### ISSUE TITLE
Implement subscriptions support

### ISSUE THREAD

**Issue by pedrofranceschi** [pagarme/pagarme-java#1]
Abstract logic for validating/processing credit card data between subscriptions and transactions in a TransactionCommon class (like Ruby library).

**Comment by adrianoluis** [comment]
I would like to know why you guys took my code and didn't kept my authorship. Is really sad to see something that you've done being used but not giving you the credit of.

**Comment by felquis** [comment]
A lib atual tem suporte completo a subscriptions :D
