### ISSUE TITLE
Erro ao gerar boleto

### ISSUE THREAD

**Issue by viniciuscst** [pagarme/pagarme-java#130]
Pessoal, ao tentar gerar uma transação com boleto é lançada a exceção 

`me.pagar.model.PagarMeException: "address" is not allowed. "addresses" is not allowed. "phone" is not allowed. "phones" is not allowed`

Já tentei removendo o endereço e o telefone e continua com o mesmo erro. O código é o seguinte:

```
    Phone phone = new Phone();
            phone.setDdd("11");
            phone.setDdi("55");
            phone.setNumber("99999999");

            String street = "Avenida Brigadeiro Faria Lima";
            String streetNumber = "1811";
            String neighborhood = "Jardim Paulistano";
            String zipcode = "01451001";
            Address address = new Address(street, streetNumber, neighborhood, zipcode);

            String name = "Aardvark Silva";
            String email = "aardvark.silva@pagar.me";
            String documentNumber = "18152564000105";
            Customer customer = new Customer(name, email);
            customer.setAddress(address);
            customer.setPhone(phone);
            customer.setDocumentNumber(documentNumber);
            customer.setType(Customer.Type.INDIVIDUAL);
            Collection<Document> documents = new ArrayList();
            Document document = new Document();

                document.setType(Document.Type.CPF);
                document.setNumber("461.296.600-73");

            documents.add(document);
            customer.setDocuments(documents);
            Map<String, Object> metadata = new HashMap<String, Object>();
            metadata.put("IdProduto", 13933139);

            Transaction tx = new Transaction();
            tx.setCustomer(customer);
            tx.setAmount(100);
            tx.setPaymentMethod(Transaction.PaymentMethod.BOLETO);
            tx.setMetadata(metadata);
            tx.setPostbackUrl("http://requestb.in/pkt7pgpk");
            tx.save();
```

**Comment by piiih** [comment]
@viniciuscst dado que provavelmente você está utilizando a última versão a API, é necessário fazer o request um pouco diferente, existe um exemplo de Java nas nossas docs, acredito que seguindo ele de tudo certo :). O formato é esse formato aqui:
```java
import java.util.ArrayList;
import java.util.Collection;
import me.pagar.model.Address;
import me.pagar.model.Billing;
import me.pagar.model.Customer;
import me.pagar.model.Document;
import me.pagar.model.Item;
import me.pagar.model.PagarMe;
import me.pagar.model.PagarMeException;
import me.pagar.model.Shipping;
import me.pagar.model.Transaction;

Transaction transaction = new Transaction();
Customer customer = new Customer();
customer.setType(Customer.Type.INDIVIDUAL);
customer.setExternalId("1001");
customer.setName("Phineas Flynn");
customer.setBirthday("1999-07-09");
customer.setEmail("phineas@threestatearea.com");
customer.setCountry("br");

Collection<Document> documents = new ArrayList();
Document document = new Document();
document.setType(Document.Type.CPF);
document.setNumber("77551442758");
documents.add(document);
customer.setDocuments(documents);

Collection<String> phones = new ArrayList();
phones.add("+5511982657575");
customer.setPhoneNumbers(phones);

Billing billing = new Billing(); 
billing.setName("Phineas Flynn");
Address address  = new Address(); 
address.setCity("Santo Andre");
address.setCountry("br");
address.setState("sp");
address.setNeighborhood("Parque Miami");
address.setStreet("Rua Rio Jari");
address.setZipcode("09133180");
address.setStreetNumber("7");
billing.setAddress(address);

Shipping shipping = new Shipping();
shipping.setAddress(address);
shipping.setName("Phineas Flynn");
shipping.setFee(3200);

Collection<Item> items = new ArrayList();
Item item = new Item(); 
item.setId("OX890");
item.setQuantity(12);
item.setTangible(Boolean.TRUE);
item.setTitle("Rockets");
item.setUnitPrice(120);

transaction.setShipping(shipping);
transaction.setBilling(billing);
transaction.setItems(items);
transaction.setPaymentMethod(Transaction.PaymentMethod.CREDIT_CARD);
transaction.setAmount(4640);
transaction.setCardHolderName("Phineas Flynn");
transaction.setCardNumber("4242424242424242");
transaction.setCardCvv("909");
transaction.setCardExpirationDate("1119"); 
transaction.setCustomer(customer);
transaction.save();
```

**Comment by viniciuscst** [comment]
> @viniciuscst dado que provavelmente você está utilizando a última versão a API, é necessário fazer o request um pouco diferente, existe um exemplo de Java nas nossas docs, acredito que seguindo ele de tudo certo :). O formato é esse formato aqui:
> 
> ```java
> import java.util.ArrayList;
> import java.util.Collection;
> import me.pagar.model.Address;
> import me.pagar.model.Billing;
> import me.pagar.model.Customer;
> import me.pagar.model.Document;
> import me.pagar.model.Item;
> import me.pagar.model.PagarMe;
> import me.pagar.model.PagarMeException;
> import me.pagar.model.Shipping;
> import me.pagar.model.Transaction;
> 
> Transaction transaction = new Transaction();
> Customer customer = new Customer();
> customer.setType(Customer.Type.INDIVIDUAL);
> customer.setExternalId("1001");
> customer.setName("Phineas Flynn");
> customer.setBirthday("1999-07-09");
> customer.setEmail("phineas@threestatearea.com");
> customer.setCountry("br");
> 
> Collection<Document> documents = new ArrayList();
> Document document = new Document();
> document.setType(Document.Type.CPF);
> document.setNumber("77551442758");
> documents.add(document);
> customer.setDocuments(documents);
> 
> Collection<String> phones = new ArrayList();
> phones.add("+5511982657575");
> customer.setPhoneNumbers(phones);
> 
> Billing billing = new Billing(); 
> billing.setName("Phineas Flynn");
> Address address  = new Address(); 
> address.setCity("Santo Andre");
> address.setCountry("br");
> address.setState("sp");
> address.setNeighborhood("Parque Miami");
> address.setStreet("Rua Rio Jari");
> address.setZipcode("09133180");
> address.setStreetNumber("7");
> billing.setAddress(address);
> 
> Shipping shipping = new Shipping();
> shipping.setAddress(address);
> shipping.setName("Phineas Flynn");
> shipping.setFee(3200);
> 
> Collection<Item> items = new ArrayList();
> Item item = new Item(); 
> item.setId("OX890");
> item.setQuantity(12);
> item.setTangible(Boolean.TRUE);
> item.setTitle("Rockets");
> item.setUnitPrice(120);
> 
> transaction.setShipping(shipping);
> transaction.setBilling(billing);
> transaction.setItems(items);
> transaction.setPaymentMethod(Transaction.PaymentMethod.CREDIT_CARD);
> transaction.setAmount(4640);
> transaction.setCardHolderName("Phineas Flynn");
> transaction.setCardNumber("4242424242424242");
> transaction.setCardCvv("909");
> transaction.setCardExpirationDate("1119"); 
> transaction.setCustomer(customer);
> transaction.save();
> ```

Deu certo

**Comment by viniciuscst** [comment]
> @viniciuscst dado que provavelmente você está utilizando a última versão a API, é necessário fazer o request um pouco diferente, existe um exemplo de Java nas nossas docs, acredito que seguindo ele de tudo certo :). O formato é esse formato aqui:
> 
> ```java
> import java.util.ArrayList;
> import java.util.Collection;
> import me.pagar.model.Address;
> import me.pagar.model.Billing;
> import me.pagar.model.Customer;
> import me.pagar.model.Document;
> import me.pagar.model.Item;
> import me.pagar.model.PagarMe;
> import me.pagar.model.PagarMeException;
> import me.pagar.model.Shipping;
> import me.pagar.model.Transaction;
> 
> Transaction transaction = new Transaction();
> Customer customer = new Customer();
> customer.setType(Customer.Type.INDIVIDUAL);
> customer.setExternalId("1001");
> customer.setName("Phineas Flynn");
> customer.setBirthday("1999-07-09");
> customer.setEmail("phineas@threestatearea.com");
> customer.setCountry("br");
> 
> Collection<Document> documents = new ArrayList();
> Document document = new Document();
> document.setType(Document.Type.CPF);
> document.setNumber("77551442758");
> documents.add(document);
> customer.setDocuments(documents);
> 
> Collection<String> phones = new ArrayList();
> phones.add("+5511982657575");
> customer.setPhoneNumbers(phones);
> 
> Billing billing = new Billing(); 
> billing.setName("Phineas Flynn");
> Address address  = new Address(); 
> address.setCity("Santo Andre");
> address.setCountry("br");
> address.setState("sp");
> address.setNeighborhood("Parque Miami");
> address.setStreet("Rua Rio Jari");
> address.setZipcode("09133180");
> address.setStreetNumber("7");
> billing.setAddress(address);
> 
> Shipping shipping = new Shipping();
> shipping.setAddress(address);
> shipping.setName("Phineas Flynn");
> shipping.setFee(3200);
> 
> Collection<Item> items = new ArrayList();
> Item item = new Item(); 
> item.setId("OX890");
> item.setQuantity(12);
> item.setTangible(Boolean.TRUE);
> item.setTitle("Rockets");
> item.setUnitPrice(120);
> 
> transaction.setShipping(shipping);
> transaction.setBilling(billing);
> transaction.setItems(items);
> transaction.setPaymentMethod(Transaction.PaymentMethod.CREDIT_CARD);
> transaction.setAmount(4640);
> transaction.setCardHolderName("Phineas Flynn");
> transaction.setCardNumber("4242424242424242");
> transaction.setCardCvv("909");
> transaction.setCardExpirationDate("1119"); 
> transaction.setCustomer(customer);
> transaction.save();
> ```

Deu certo @piiih, mas agora quando eu seto a  PostbackUrl ele não retorna a url do boleto.
