### ISSUE TITLE
CVV param with type integer

### ISSUE THREAD

**Issue by Matheus-Maciel** [pagarme/pagarme-java#137]
### CONTEXTO
O SDK possui o campo CVV que é do tipo inteiro (integer) ao invés de texto (string).

### ATUAL

Por conta dessa tipagem incorreta são gerados erros para casos iniciados em zero aonde o CVV 088 se torna 88, tornando impossível transacionar com cartões que possuem o CVV que se enquadram a esse cenário.

### IDEAL

O ideal seria que o SDK tivesse esses campos como string para evitar que erros como os que ocorrem hoje.

### Proposta

Alterar a tipagem dos parâmetros contidos no SDK

**Comment by LucasLyoji** [comment]
Essa issue foi resolvida com o PR [#138](https://github.com/pagarme/pagarme-java/pull/138)
