### ISSUE TITLE
 When will release version 2.0 on maven?

### ISSUE THREAD

**Issue by vanialadev** [pagarme/pagarme-java#147]

**Comment by jonatasmaxi** [comment]
Hey there, we're planning to upload this version to maven this week

**Comment by jonatasmaxi** [comment]
<dependency>
  <groupId>me.pagar</groupId>
  <artifactId>pagarme-java</artifactId>
  <version>2.1.0</version>
</dependency> 
Just uploaded, if you have any problem please let me know
