### ISSUE TITLE
BankAccount doesn't allow null value in AgenciaDv field.

### ISSUE THREAD

**Issue by tiagofilipe3** [pagarme/pagarme-java#55]
BankAccount doesn't allow null value in AgenciaDv field and throws UnsupportedOperation exception.

**Comment by vagnervst** [comment]
Olá @tiagofilipe3, tudo bem?

Meu nome é Vagner, faço parte da equipe de Suporte Técnico aqui do Pagar.me.

Executei os testes com a versão atual de nossa lib, e não recebi um exception com `agenciaDv` como `null`, dado que este é o valor default em nossa API. O problema persiste?

Abraços!
