### ISSUE TITLE
Erro na criação de cliente

### ISSUE THREAD

**Issue by Thiagokairala** [pagarme/pagarme-java#67]
Ao tentar criar um cliente, a seguinte exception é disparada:

me.pagar.model.PagarMeException: child "external_id" fails because ["external_id" is required]

porém na lib não existe o campo external_id para que possa ser setado

**Comment by jonatasmaxi** [comment]
Olá Thiago, tudo bem? 

Meu nome é Jonatas e faço parte da equipe de suporte técnico do Pagar.me. 

Esse erro acontece por conta da versão da sua chave de API ser a 2017-08-28 e esta ainda não é compatível com a lib de Java ainda.  

Informamos que estamos trabalhando para adaptar a biblioteca para se adequar às novas modificações da API porém, no momento, para que você não possua maiores problemas com a integração recomendamos que solicite o downgrade da versão da sua chave de API para versão 2017-07 no email relacionamento@pagar.me
Lembrando que essa solicitação precisa ser feita através de um e-mail com privilégios de administrador da conta. 

Agradecemos pelo feedback e caso tenha mais alguma dúvida fico à disposição no e-mail suporte@pagar.me
