### ISSUE TITLE
Erro ao realizar uma transação

### ISSUE THREAD

**Issue by mateussaid** [pagarme/pagarme-java#75]
Boa tarde, 
Estamos implementando uma funcionalidade de pagamento em nosso sistema, e para isso pretendemos utilizar a solução pagar.me, porém ao tentar realizar uma transação `transaction.save()`, a API sempre retorna o erro: 

> me.pagar.model.PagarMeException: "value" is required

Criamos uma conta teste para termos acesso ao Dashboard e a versão da API é "2017-08-28" (Live/Test).

Verifiquei também que no Checkout disponibilizado via JS pela pagar.me (https://docs.pagar.me/docs/overview-checkout) Também está ocorrendo o erro.

Como podemos solucionar este problema? Pois o mesmo está inviabilizando o uso da solução pagar.me.

Grato.

**Comment by jonatasmaxi** [comment]
Olá @mateussaid tudo bom?

 Meu nome é Jonatas e faço parte da equipe de suporte do Pagar.me. 

Este erro acontece devido a falta de algum parâmetro obrigatório na criação da transação, peço gentilmente que tente utilizar o código abaixo para criar a transação: 
 
       Transaction transaction = new Transaction();
        Customer customer = new Customer();
        customer.setType(Customer.Type.INDIVIDUAL);
        customer.setExternalId("1001");
        customer.setName("Phineas Flynn");
        customer.setBirthday("1999-07-09");
        customer.setEmail("phineas@threestatearea.com");
        customer.setCountry("br");

        Collection<Document> documents = new ArrayList();
        Document document = new Document();
        document.setType(Document.Type.CPF);
        document.setNumber("77551442758");
        documents.add(document);
        customer.setDocuments(documents);

        Collection<String> phones = new ArrayList();
        phones.add("+5511982657575");
        customer.setPhoneNumbers(phones);

        Billing billing = new Billing(); 
        billing.setName("Phineas Flynn");
        Address address  = new Address(); 
        address.setCity("Santo Andre");
        address.setCountry("br");
        address.setState("sp");
        address.setNeighborhood("Parque Miami");
        address.setStreet("Rua Rio Jari");
        address.setZipcode("09133180");
        address.setStreetNumber("7");
        billing.setAddress(address);
        
        Shipping shipping = new Shipping();
        shipping.setAddress(address);
        shipping.setNa   Transaction transaction = new Transaction();
        Customer customer = new Customer();
        customer.setType(Customer.Type.INDIVIDUAL);
        customer.setExternalId("1001");
        customer.setName("Phineas Flynn");
        customer.setBirthday("1999-07-09");
        customer.setEmail("phineas@threestatearea.com");
        customer.setCountry("br");

        Collection<Document> documents = new ArrayList();
        Document document = new Document();
        document.setType(Document.Type.CPF);
        document.setNumber("77551442758");
        documents.add(document);
        customer.setDocuments(documents);

        Collection<String> phones = new ArrayList();
        phones.add("+5511982657575");
        customer.setPhoneNumbers(phones);

        Billing billing = new Billing(); 
        billing.setName("Phineas Flynn");
        Address address  = new Address(); 
        address.setCity("Santo Andre");
        address.setCountry("br");
        address.setState("sp");
        address.setNeighborhood("Parque Miami");
        address.setStreet("Rua Rio Jari");
        address.setZipcode("09133180");
        address.setStreetNumber("7");
        billing.setAddress(address);
        
        Shipping shipping = new Shipping();
        shipping.setAddress(address);
        shipping.setName("Phineas Flynn");
        shipping.setFee(3200);
        
        Collection<Item> items = new ArrayList();
        Item item = new Item(); 
        item.setId("OX890");
        item.setQuantity(12);
        item.setTangible(Boolean.TRUE);
        item.setTitle("Rockets");
        item.setUnitPrice(120);
        transaction.setShipping(shipping);
        transaction.setBilling(billing);
        transaction.setItems(items);
        transaction.setPaymentMethod(Transaction.PaymentMethod.CREDIT_CARD);
        transaction.setAmount(4640);
        transaction.setCardHolderName("Phineas Flynn");
        transaction.setCardNumber("4242424242424242");
        transaction.setCardCvv("909");
        transaction.setCardExpirationDate("1119"); 
        transaction.setCustomer(customer);
        transaction.save();me("Phineas Flynn");
        shipping.setFee(3200);
        
        Collection<Item> items = new ArrayList();
        Item item = new Item(); 
        item.setId("OX890");
        item.setQuantity(12);
        item.setTangible(Boolean.TRUE);
        item.setTitle("Rockets");
        item.setUnitPrice(120);
        transaction.setShipping(shipping);
        transaction.setBilling(billing);
        transaction.setItems(items);
        transaction.setPaymentMethod(Transaction.PaymentMethod.CREDIT_CARD);
        transaction.setAmount(4640);
        transaction.setCardHolderName("Phineas Flynn");
        transaction.setCardNumber("4242424242424242");
        transaction.setCardCvv("909");
        transaction.setCardExpirationDate("1119"); 
        transaction.setCustomer(customer);
        transaction.save();

Vale lembrar que o suporte para a versão 2018-08-28 para o SDK de Java foi adicionado recentemente #70 portanto, é necessário verificar se o SDK utilizado está atualizado. 

Qualquer dúvida estou à disposição. 

Abraços.

**Comment by mateussaid** [comment]
Bom Dia @jonatasmaxi 
Obrigado pela resposta, vou realizar o teste. 
Você poderia atualizar o [Maven Central Repository](https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22me.pagar%22%20AND%20a%3A%22pagarme-java%22), com a API atualizada? A última atualização la está do dia (04-Dec-2017). 
Estamos fazendo a importação da dependência via Gradle.
Obrigado

**Comment by jonatasmaxi** [comment]
Olá @mateussaid, 

Iremos efetuar a atualização em breve. 

Aviso assim que o procedimento for realizado, ok?

Qualquer dúvida estou à disposição. 

Abraços.

**Comment by mateussaid** [comment]
Ok @jonatasmaxi , fico no aguardo para darmos continuidade a integração. Obrigado

**Comment by mateussaid** [comment]
Bom dia @jonatasmaxi,
Temos uma previsão para essa atualização do repositório? pois estamos bloqueados.
Obrigado

**Comment by jonatasmaxi** [comment]
Olá @mateussaid está atuliazado por lá.

Também atualizei o exemplo de um dos meus comentários anteriores, alguns campos foram duplicados, desculpe.

Se precisar de mais alguma coisa estou à disposição. 
Att.

**Comment by mateussaid** [comment]
Boa tarde
@jonatasmaxi com a atualização funcionou. Obrigado pelo rápido suporte.
- Temos algum documento atualizando explicando os atributos da API ? (se são obrigatórios, quando devemos utilizar etc...) ?
- Existe uma forma de implementarmos a funcionalidade "one click buy", via a API java?

Grato

**Comment by jonatasmaxi** [comment]
Olá @mateussaid  boa tarde. 

Temos a nossa documentação, ela está disponível no endereço: https://docs.pagar.me/
Você também pode dar uma olhadinha na nossa referência completa. ela fica disponível aqui: 
https://docs.pagar.me/v2017-08-28/reference

Os exemplos de Java para criação de Transação e Customer ainda não foram adicionados, mas se precisar de alguma coisa em relação a isso estou aqui. 

Sobre a sua segunda questão, sim. É possível implementar a funcionalidade one click buy através do SDK de Java. 

Para fazer isso, primeiramente você deve criar um cartão através da rota /cards (veja detalhes de como fazer isso aqui: https://docs.pagar.me/v2017-08-28/reference#criando-um-cartao). Na response da criação do cartão será retornado o card_id, um identificador dos dados do cartão que foram salvos por aqui, Sempre que quiser realizar uma transação neste cartão, envie este card_id na criação da transação/assinatura e pronto.  

Se tiver mais alguma dúvida sobre isso dê uma olhadinha nesta página: 
https://docs.pagar.me/docs/realizando-uma-transacao-de-cartao-de-credito#section-criando-um-cart%C3%A3o-para-one-click-buy 

Faz sentido?

Qualquer dúvida estou à disposição. 
Abraços.

**Comment by mateussaid** [comment]
Certo @jonatasmaxi. 
Vou fechar a Issue.
Muito obrigado, qualquer dúvida entrarei em contato.
